2022-07-22 11:30:22,025 |  logger |  ERROR |  Error in twitter login: HTTPConnectionPool(host='localhost', port=56688): Max retries exceeded with url: /session/5914d8064f921b4bea53682e6e28367b/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa6c690ddf0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2022-07-22 11:30:22,035 |  logger |  ERROR |  Error in posting tweet: HTTPConnectionPool(host='localhost', port=56688): Max retries exceeded with url: /session/5914d8064f921b4bea53682e6e28367b/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa6c690d880>: Failed to establish a new connection: [Errno 61] Connection refused'))
2022-07-22 11:30:32,044 |  logger |  ERROR |  Error in twitter login: HTTPConnectionPool(host='localhost', port=56688): Max retries exceeded with url: /session/5914d8064f921b4bea53682e6e28367b/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa6c692e5b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2022-07-22 11:30:32,053 |  logger |  ERROR |  Error in posting tweet: HTTPConnectionPool(host='localhost', port=56688): Max retries exceeded with url: /session/5914d8064f921b4bea53682e6e28367b/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa6c690dcd0>: Failed to establish a new connection: [Errno 61] Connection refused'))
